services:
  mysql:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
    build:
      context: mysql
    healthcheck:
      test: ['CMD', 'sh', '-c', 'exec mysqladmin ping --host 127.0.0.1 --password=$${MYSQL_ROOT_PASSWORD}']
      interval: 500ms
      start_interval: 100ms
      start_period: 10s
  tango-cs:
    image: registry.gitlab.com/tango-controls/docker/tango-cs:9.3.5
    ports:
     - "10000:10000"
    environment:
     - TANGO_HOST=localhost:10000
     - MYSQL_HOST=mysql:3306
     - MYSQL_USER=tango
     - MYSQL_PASSWORD=tango
     - MYSQL_DATABASE=tango
    command: ['/usr/bin/supervisord', '-c', '/etc/supervisord.conf']
    depends_on:
      mysql:
        condition: service_healthy
  micromax-ds:
    image: micromax-ds
    environment:
     - TANGO_HOST=tango-cs:10000
    build:
      context: micromax-ds
    depends_on:
     - tango-cs
  mysql-2:
    image: registry.gitlab.com/tango-controls/docker/mysql:5
    environment:
     - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ['CMD', 'sh', '-c', 'exec mysqladmin ping --host 127.0.0.1 --password=$${MYSQL_ROOT_PASSWORD}']
      interval: 500ms
      start_interval: 100ms
      start_period: 10s
  g-v-csproxy-0:
    image: registry.gitlab.com/tango-controls/docker/tango-cs:9.3.5
    environment:
     - TANGO_HOST=localhost:10000
     - MYSQL_HOST=mysql-2:3306
     - MYSQL_USER=tango
     - MYSQL_PASSWORD=tango
     - MYSQL_DATABASE=tango
    depends_on:
      mysql-2:
        condition: service_healthy
    command: ['/usr/bin/supervisord', '-c', '/etc/supervisord.conf']
  # runs 'g-v-csproxy-0' tango device servers
  csproxy-ds:
    image: csproxy-ds
    environment:
     - TANGO_HOST=g-v-csproxy-0:10000
    build:
      context: csproxy-ds
  mxcube:
    image: mxcube
    ports:
     - "8081:8081"
     - '3000:3000'  # For the `npm run start` frontend variant with hot reload
    environment:
     - TANGO_HOST=tango-cs:10000
    build:
      context: mxcube
    volumes:
      - source: './mxcube/cfg-maxiv-mxcubecore'
        target: '/app/conf'
        type: bind
      - source: './mxcube/mxcubecore'
        target: '/app/core'
        type: bind
      - source: './mxcube/mxcube3'
        target: '/app/web'
        type: bind
  b-micromax-md3-pc:
    image: b-micromax-md3-pc
    build:
      context: b-micromax-md3-pc
  b-micromax-isara-0:
    image: b-micromax-isara-0
    build:
      context: b-micromax-isara-0
  dbg:
    image: dbg
    environment:
     - TANGO_HOST=tango-cs:10000
    build:
      context: dbg
